# config.yaml
# Central configuration file for HerpAI agents and system settings

default_model_provider: claude

agents:
  virology:
    model_provider: claude
    model: claude-sonnet-3.7
  drug_design:
    model_provider: gpt
    model: gpt-4
  crispr:
    model_provider: claude
    model: claude-sonnet-3.7
  target_prioritization:
    model_provider: claude
    model: claude-sonnet-3.7
  delivery:
    model_provider: claude
    model: claude-sonnet-3.7

simulation:
  max_tokens: 1000
  temperature: 0.4

logging:
  level: INFO
