name: CD Pipeline

on:
  workflow_run:
    workflows: [ci-pipeline-push]
    types: [completed]
   
  workflow_dispatch: # Allow manual triggering
    inputs:
      version:
        description: Version to release (optional)
        required: false
        default: 'false'

jobs:
  # checks if the files/paths were modified
  changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      docker: ${{ steps.filter.outputs.docker }}
    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          docker:
            - 'agents/**'
            - 'consumers/**'
            - 'core/**'
            - 'orchestrator/**'
            - 'prompts/**'
            - 'requirements/**'
            - 'src/**'
            - 'templates/**'
            - 'tests/**'
            - 'entrypoint.sh'
            - 'Dockerfile'
            - '.github/workflows/deploy.yaml'

  # checks if the files/paths were modified
  validate:
    env:
      CI_PIPELINE: ${{ github.event.workflow_run.conclusion == 'success' && 'true || 'false' }}
      DOCKER_FILES: ${{ needs.changes.outputs.docker == 'true' == 'success' && 'true || 'false' }}
      MAIN_BRANCH: ${{ github.ref == 'refs/heads/main' == 'success' && 'true || 'false' }}
    
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      docker: ${{ steps.validate.outputs.docker }}
    steps:
      - name: Echo CI Pipeline
        run: echo "CI Pipeline status = $CI_PIPELINE"

      - name: Echo docker files
        run: echo "Docker files modified = $DOCKER_FILES"

      - name: Echo main branch
        run: echo "Is main branch = $MAIN_BRANCH"
        
      - if: ${{ CI_PIPELINE == 'true' && DOCKER == 'true' && MAIN_BRANCH == 'true' }}
        name: Set output to true
        run: echo 'true' >> "$GITHUB_OUTPUT"
      

  build-and-push:
    if: ${{ needs.validate.outputs.docker == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Required for pushing to GHCR

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Short Commit SHA
        run: echo "GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/herpai-app .

      - name: Add Tags to the Image
        run: |
          docker tag ghcr.io/${{ github.repository_owner }}/herpai-app ghcr.io/${{ github.repository_owner }}/herpai-app:latest
          docker tag ghcr.io/${{ github.repository_owner }}/herpai-app ghcr.io/${{ github.repository_owner }}/herpai-app:${{ env.GIT_SHA }}

      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/herpai-app:latest
          docker push ghcr.io/${{ github.repository_owner }}/herpai-app:${{ env.GIT_SHA }}

